title = "Houze ZHANG"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = 'ananke'

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Houze ZHANG"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/houzezhang"
